server:
  port: 8081

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        # Ur Services here 
        - id: user_route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /${segment}
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
